package ddit.chater05.sec06;
//09.01
public enum Day {
	MONDAY, TUSEDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY;
}

	enum Month{
		JUNURARY, FEBRUARY, MARCH, APRIL, MAY, JUNE, 
		JULY, AUGUST, SEPTEMBER, OTCTOBER, NOVEMBER, DECEMBER;
	}
